//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int PatientId { get; set; }
        public string TypeOfAction { get; set; }
        public string TypeOfWorkFlow { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime AccessedDTTM { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
