//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int doctorId { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middle { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string phoneNumber { get; set; }
        public string emergencyphonenumber { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string specialist { get; set; }
        public System.DateTime addedOn { get; set; }
    }
}
